apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  generateName: tfjob-multi-
  namespace: distributed-tf
spec:
  cleanPodPolicy: Running
  tfReplicaSpecs:
    Worker:
      replicas: 2
      restartPolicy: Never
      template:
        metadata:
          annotations:
          sidecar.istio.io/inject: "false"
        spec:
          containers:
          - name: tensorflow
            image: "quay.io/cep235/tensorflow-fashion-mnist:latest"
            command: ["python3", "/opt/setup/scripts/fashion_mnist.py", "100", "10", "32", "2"] 
            imagePullPolicy: Always
            env:
              - name: LD_LIBRARY_PATH
                value: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/home/nccl/lib:/usr/local/cuda/lib:/usr/local/cuda-10.1/compat
          imagePullSecrets:
            - name: "my-quay-key"
          nodeSelector:
            beta.kubernetes.io/instance-type: "g4dn.xlarge"
